import React, { useState, useEffect, useRef } from "react";
import axios from "axios";
import { motion } from "framer-motion";
import { RefreshCw, Download } from "lucide-react";
import {
  PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer,
} from "recharts";
import jsPDF from "jspdf";

const COLORS = { debt: "#ef4444", goal: "#22c55e", invest: "#8b5cf6" };

export default function AIAllocationPlan({ userId, userName = "User", triggerKey }) {
  const [allocation, setAllocation] = useState(null);
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const hasFetched = useRef(false);

  // ── Auto-generate whenever triggerKey changes (savings/debts/goals updated) ──
  useEffect(() => {
    if (!userId) return;
    // small debounce so rapid saves don't spam the API
    const timer = setTimeout(() => fetchAIPlan(), 800);
    return () => clearTimeout(timer);
  }, [triggerKey, userId]);

  const fetchAIPlan = async () => {
    setLoading(true);
    try {
      const res = await axios.get(
        `http://localhost:8000/financial-manager/analyze/${userId}`
      );
      setAllocation(res.data.ai_analysis || null);
    } catch (err) {
      console.error("AI plan fetch error:", err);
    } finally {
      setLoading(false);
    }
  };

  // ── PDF: pure jsPDF text — no canvas, no SVG issues ──────────────────────
  const handleDownloadPDF = () => {
    if (!allocation) return;
    setDownloading(true);

    try {
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const W = doc.internal.pageSize.getWidth();
      let y = 15;

      const line = (text, x = 14, size = 11, style = "normal", color = [7, 33, 70]) => {
        doc.setFont("helvetica", style);
        doc.setFontSize(size);
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(text, W - 28);
        doc.text(lines, x, y);
        y += lines.length * (size * 0.45) + 2;
      };

      const gap = (n = 4) => { y += n; };
      const checkPage = () => { if (y > 270) { doc.addPage(); y = 15; } };

      // Header
      doc.setFillColor(7, 33, 70);
      doc.rect(0, 0, W, 22, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(255, 255, 255);
      doc.text("AI Financial Allocation Report", 14, 14);
      y = 30;

      line(`User: ${userName}`, 14, 10, "normal", [80, 80, 80]);
      line(`Date: ${new Date().toLocaleDateString("en-IN")}`, 14, 10, "normal", [80, 80, 80]);
      gap(4);

      // Summary
      doc.setDrawColor(31, 162, 182);
      doc.setLineWidth(0.5);
      doc.line(14, y, W - 14, y);
      gap(4);
      line("Summary", 14, 13, "bold", [7, 33, 70]);
      gap(1);
      line(allocation.summary || "—", 14, 10, "normal", [50, 50, 50]);
      gap(5);
      checkPage();

      // Allocation table
      doc.line(14, y, W - 14, y);
      gap(4);
      line("Monthly Allocation Breakdown", 14, 13, "bold", [7, 33, 70]);
      gap(2);

      (allocation.allocation || []).forEach((a, i) => {
        checkPage();
        const tag = a.type === "debt" ? "[DEBT]" : "[GOAL]";
        const tagColor = a.type === "debt" ? [239, 68, 68] : [34, 197, 94];
        line(`${i + 1}. ${a.title}`, 14, 11, "bold", [7, 33, 70]);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...tagColor);
        doc.text(tag, W - 30, y - 5);
        line(`   Allocation: Rs ${(a.suggested_allocation || 0).toLocaleString("en-IN")}/mo`, 14, 10, "normal", [50, 50, 50]);
        line(`   Est. completion: ${a.estimated_months} months`, 14, 10, "normal", [50, 50, 50]);
        if (a.strategy) line(`   Strategy: ${a.strategy}`, 14, 9, "italic", [100, 100, 100]);
        gap(3);
      });

      // Investment suggestion
      if (allocation.investment_suggestion) {
        checkPage();
        doc.line(14, y, W - 14, y);
        gap(4);
        line("Investment Suggestion", 14, 13, "bold", [7, 33, 70]);
        gap(1);
        const inv = allocation.investment_suggestion;
        line(`Type: ${inv.type}  |  Amount: Rs ${(inv.amount || 0).toLocaleString("en-IN")}/mo`, 14, 10, "normal", [50, 50, 50]);
        if (inv.reason) line(`Reason: ${inv.reason}`, 14, 9, "italic", [100, 100, 100]);
        gap(5);
      }

      // Footer
      doc.setFillColor(245, 247, 250);
      doc.rect(0, 282, W, 15, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by AI Financial Planner  |  For informational purposes only", 14, 289);

      doc.save(`${userName}_AI_Allocation_Report.pdf`);
    } catch (err) {
      console.error("PDF error:", err);
      alert("PDF generation failed. Please try again.");
    } finally {
      setDownloading(false);
    }
  };

  // ── Chart data ────────────────────────────────────────────────────────────
  const chartData = allocation
    ? [
        ...(allocation.allocation || []).map((a) => ({
          name: a.title,
          value: a.suggested_allocation,
          type: a.type,
        })),
        ...(allocation.investment_suggestion
          ? [{ name: allocation.investment_suggestion.type, value: allocation.investment_suggestion.amount, type: "invest" }]
          : []),
      ]
    : [];

  return (
    <motion.div
      className="bg-white rounded-2xl p-6 shadow-md border sticky top-6 h-fit"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      {/* Header */}
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-lg font-semibold text-[#072146]">📊 AI Allocation Plan</h2>
        <div className="flex gap-2">
          {/* Regenerate always visible */}
          <button
            onClick={fetchAIPlan}
            disabled={loading}
            className={`flex items-center gap-2 px-3 py-1 rounded-lg text-sm font-medium transition ${
              loading ? "bg-gray-300 cursor-not-allowed text-gray-500" : "bg-[#1FA2B6] text-white hover:bg-[#148a9c]"
            }`}
          >
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
            {loading ? "Analyzing..." : "Regenerate"}
          </button>

          {/* Download only when plan exists */}
          {allocation && (
            <button
              onClick={handleDownloadPDF}
              disabled={downloading}
              className={`flex items-center gap-2 px-3 py-1 rounded-lg text-sm font-medium transition ${
                downloading ? "bg-gray-300 cursor-not-allowed text-gray-500" : "bg-[#072146] text-white hover:bg-[#0a305f]"
              }`}
            >
              <Download size={14} />
              {downloading ? "Generating..." : "Download PDF"}
            </button>
          )}
        </div>
      </div>

      {/* Body */}
      {loading && !allocation ? (
        <div className="flex flex-col items-center justify-center py-10 text-gray-400 gap-3">
          <RefreshCw size={28} className="animate-spin text-[#1FA2B6]" />
          <p className="text-sm">Analyzing your finances...</p>
        </div>
      ) : !allocation ? (
        <p className="text-gray-400 text-sm text-center py-6">
          Add your savings, debts, or goals — plan will generate automatically.
        </p>
      ) : (
        <>
          {/* Summary */}
          <div className="bg-[#F0F9FB] border border-[#1FA2B6]/30 rounded-xl p-3 mb-4">
            <p className="text-[#072146] text-sm leading-relaxed">{allocation.summary}</p>
          </div>

          {/* Pie Chart */}
          {chartData.length > 0 && (
            <div className="my-4 bg-[#F8FAFC] rounded-xl p-4">
              <h3 className="text-[#072146] font-semibold mb-3 text-center">💹 Monthly Savings Allocation</h3>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={chartData}
                    dataKey="value"
                    nameKey="name"
                    cx="50%"
                    cy="50%"
                    outerRadius={110}
                    innerRadius={55}
                    paddingAngle={3}
                    label={({ name, value }) => `${name}: ₹${value.toLocaleString("en-IN")}`}
                  >
                    {chartData.map((entry, i) => (
                      <Cell
                        key={i}
                        fill={COLORS[entry.type] || "#94a3b8"}
                        stroke="white"
                        strokeWidth={2}
                      />
                    ))}
                  </Pie>
                  <Tooltip formatter={(v) => `₹${v.toLocaleString("en-IN")}`} />
                  <Legend verticalAlign="bottom" height={36} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          )}

          {/* Breakdown */}
          <div className="space-y-3 mt-2">
            {allocation.allocation?.map((a, i) => (
              <div key={i} className="border rounded-xl p-3 flex justify-between items-center shadow-sm hover:shadow-md transition">
                <div>
                  <p className="capitalize font-medium text-[#072146]">
                    {a.title}{" "}
                    <span className={`text-xs ml-2 px-2 py-0.5 rounded ${a.type === "debt" ? "bg-red-100 text-red-600" : "bg-green-100 text-green-600"}`}>
                      {a.type}
                    </span>
                  </p>
                  <p className="text-xs text-gray-500">
                    Est. {a.estimated_months} months — <span className="italic">{a.strategy}</span>
                  </p>
                </div>
                <p className="text-[#1FA2B6] font-semibold">₹{a.suggested_allocation.toLocaleString("en-IN")}/mo</p>
              </div>
            ))}
          </div>

          {/* Investment Suggestion */}
          {allocation.investment_suggestion && (
            <div className="mt-4 p-4 border border-[#1FA2B6]/40 bg-[#F4F8FA] rounded-xl">
              <h3 className="text-[#072146] font-semibold mb-1">💡 Investment Suggestion</h3>
              <p className="text-sm text-gray-700">
                <span className="font-medium text-[#1FA2B6]">{allocation.investment_suggestion.type}</span>
                {" "}— Invest ₹{allocation.investment_suggestion.amount.toLocaleString("en-IN")} monthly.
              </p>
              <p className="text-xs text-gray-500 mt-1 italic">{allocation.investment_suggestion.reason}</p>
            </div>
          )}
        </>
      )}
    </motion.div>
  );
}
